name: Check &amp; deploy API documentation
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bump-sh/github-action@v1
        with:
          doc: board-games-api
          token: e3ffb2bf8e870e0cf892e4feedb86be6
          file: BoardGameAPI.yaml
  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bump-sh/github-action@v1
        with:
          doc: board-games-api
          token: e3ffb2bf8e870e0cf892e4feedb86be6
          file: BoardGameAPI.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}